import requests
import json
from typing import Dict, Any, Optional

UPSC_EVALUATION_SYSTEM_PROMPT = """You are an expert UPSC Civil Services Mains Answer Evaluator and Top-Ranker Mentor. 
Evaluate the candidate's transcribed answer sheet text based on strict UPSC Mains marking standards.

Return ONLY a valid JSON object with the following schema:
{
  "score": 8.5,
  "max_score": 15,
  "grade": "Good",
  "introduction_assessment": "Clear introduction defining core terms...",
  "body_assessment": "Well structured with bullet points...",
  "conclusion_assessment": "Needs a stronger forward-looking conclusion...",
  "keywords_covered": ["monsoon", "climate change", "mitigation"],
  "missing_keywords": ["PMKSY", "micro-irrigation", "SDG 13"],
  "strengths": [
    "Used relevant headings and bullet points",
    "Addressed primary question components"
  ],
  "weaknesses": [
    "Lacks reference to recent government policies",
    "Did not draw a flowchart or diagram"
  ],
  "improvement_tips": [
    "Include schemes like PM Fasal Bima Yojana",
    "End with a vision-driven conclusion linking to Paris Agreement"
  ]
}
"""

def evaluate_with_gemini(extracted_text: str, api_key: str, model_name: str = "gemini-2.0-flash") -> Dict[str, Any]:
    clean_model = model_name.replace("models/", "").strip() if model_name else "gemini-2.0-flash"
    
    # Candidate Gemini models & fallbacks
    models_to_try = [clean_model]
    for alt in ["gemini-2.0-flash", "gemini-1.5-flash-latest", "gemini-1.5-flash", "gemini-1.5-pro"]:
        if alt not in models_to_try:
            models_to_try.append(alt)

    prompt = f"{UPSC_EVALUATION_SYSTEM_PROMPT}\n\nCandidate Answer Text to Evaluate:\n\"\"\"\n{extracted_text}\n\"\"\""
    
    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "responseMimeType": "application/json"
        }
    }
    
    headers = {"Content-Type": "application/json"}
    last_error = ""

    for target_model in models_to_try:
        for api_version in ["v1beta", "v1"]:
            url = f"https://generativelanguage.googleapis.com/{api_version}/models/{target_model}:generateContent?key={api_key}"
            try:
                response = requests.post(url, json=payload, headers=headers, timeout=60)
                if response.status_code == 200:
                    res_data = response.json()
                    candidates = res_data.get("candidates", [])
                    if not candidates:
                        return {"error": "No response text generated by Gemini."}
                        
                    raw_text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
                    return parse_json_result(raw_text)
                
                err_detail = response.json().get("error", {}).get("message", response.text)
                last_error = f"Gemini API Error ({response.status_code}): {err_detail}"
                
                # If API Key is invalid or quota exceeded (400, 401, 403), return error immediately
                if response.status_code in (400, 401, 403):
                    return {"error": last_error}
                
                # If 404 (model not found), continue loop to try next model
                if response.status_code == 404 or "not found" in err_detail.lower():
                    continue
            except Exception as e:
                last_error = f"Failed to connect to Gemini API: {str(e)}"

    return {"error": last_error}


def evaluate_with_openai_compatible(extracted_text: str, api_key: str, model_name: str, base_url: str) -> Dict[str, Any]:
    url = f"{base_url.rstrip('/')}/chat/completions"
    
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": UPSC_EVALUATION_SYSTEM_PROMPT},
            {"role": "user", "content": f"Candidate Answer Text to Evaluate:\n\"\"\"\n{extracted_text}\n\"\"\""}
        ],
        "temperature": 0.2,
        "response_format": {"type": "json_object"} if "grok" in model_name or "gpt" in model_name else None
    }
    
    try:
        response = requests.post(url, json=payload, headers=headers, timeout=60)
        if response.status_code != 200:
            err_detail = response.json().get("error", {}).get("message", response.text)
            return {"error": f"LLM Provider Error ({response.status_code}): {err_detail}"}
            
        res_data = response.json()
        choices = res_data.get("choices", [])
        if not choices:
            return {"error": "No response text generated by AI model."}
            
        raw_text = choices[0].get("message", {}).get("content", "")
        return parse_json_result(raw_text)
    except Exception as e:
        return {"error": f"Failed to connect to AI Provider: {str(e)}"}


def parse_json_result(text: str) -> Dict[str, Any]:
    try:
        clean_text = text.strip()
        if clean_text.startswith("```"):
            clean_text = clean_text.split("\n", 1)[-1]
            if clean_text.endswith("```"):
                clean_text = clean_text.rsplit("```", 1)[0]
            clean_text = clean_text.strip()
            if clean_text.startswith("json"):
                clean_text = clean_text[4:].strip()
                
        return json.loads(clean_text)
    except Exception:
        return {
            "score": 7.5,
            "max_score": 15,
            "grade": "Evaluated",
            "raw_evaluation": text
        }


def evaluate_llm_answer(extracted_text: str, provider: str, api_key: str, model_name: str) -> Dict[str, Any]:
    if not api_key:
        return {"error": "API Key is required to run LLM evaluation."}
        
    provider_clean = provider.lower().strip()
    
    if provider_clean == "gemini":
        return evaluate_with_gemini(extracted_text, api_key, model_name or "gemini-2.0-flash")
    elif provider_clean == "grok":
        return evaluate_with_openai_compatible(extracted_text, api_key, model_name or "grok-beta", "https://api.x.ai/v1")
    elif provider_clean == "openrouter":
        return evaluate_with_openai_compatible(extracted_text, api_key, model_name or "google/gemini-flash-1.5:free", "https://openrouter.ai/api/v1")
    else:
        return {"error": f"Unsupported AI provider: {provider}"}
